#!/usr/bin/fish

# Restart whole setup
xrandr --auto

# Start to setup stuff
set xrandr_output (xrandr)

# Check for home monitors
if echo $xrandr_output | grep -q "DP-1 disconnected"
    echo "DP-1 not connected"
    exit 1
end

if echo $xrandr_output | grep -q "DP-2 disconnected"
    echo "DP-2 not connected"
    exit 1
end

# Setup left
xrandr --output DP-1 --left-of DP-2 --rotate left

# Check for first monitor resolution

xrandr --output DP-2 --mode 2560x1440
xrandr --output DP-2 --mode 3440x1440

# Close laptop monitor
xrandr --output eDP-1 --off

# Background
feh --bg-fill ~/Pictures/Wallpaper/klNLXU.png
